### PR TITLE
Update to Clojure 1.9.0-alpha17 and Clojurescript 1.9.562.

### PR DESCRIPTION
**Pull request by kennyjwilli**
This PR unblocks those of us using the latest Clojure alpha release.

### CODE REVIEW

**Comment by alex-dixon** [comment]
Thank you. This is something we've been wanting. Last time I tried it broke things.  Will review ASAP.

**Comment by kennyjwilli** [comment]
Great, thanks. I ran the same tests that CircleCI runs (`lein do test :only precept.test-runner`) and they pass. Not sure if there are other tests that need to be ran.

**Comment by alex-dixon** [comment]
You ran the right tests. Unfortunately I'm behind on CLJS tests #61 still. 

Think this was the issue I ran into before. I'm guessing it has to do with an old version of the schema library that Clara is using but I didn't look into it much:

```
WARNING: Inst already refers to: #'clojure.core/Inst in namespace: schema.core, being replaced by: #'schema.core/Inst
WARNING: Inst already refers to: cljs.core/Inst being replaced by: schema.core/Inst at line 394 target/cljsbuild/public/js/out/schema/core.cljs
WARNING: ->MapEntry already refers to: cljs.core/->MapEntry being replaced by: schema.core/->MapEntry at line 682 target/cljsbuild/public/js/out/schema/core.cljs
Successfully compiled "target/cljsbuild/public/js/app.js" in 22.862 seconds.
```
```

core.cljs:109 Uncaught Error: No protocol method Schema.spec defined for type cljs.core/PersistentArrayMap: {#schema.core.OptionalKey{:k :initial-value} #schema.core.AnythingSchema{:_ nil}, #schema.core.OptionalKey{:k :combine-fn} #schema.core.AnythingSchema{:_ nil}, #schema.core.OptionalKey{:k :convert-return-fn} #schema.core.AnythingSchema{:_ nil}, :reduce-fn #schema.core.AnythingSchema{:_ nil}, #schema.core.OptionalKey{:k :retract-fn} #schema.core.AnythingSchema{:_ nil}}
    at cljs$core$missing_protocol (core.cljs:281)
    at schema$core$spec (core.cljs:109)
    at core.cljs:134
    at schema$spec$core$run_checker (core.cljs:69)
    at schema$core$checker (core.cljs:133)
    at schema$core$validator (core.cljs:148)
    at schema$core$validate (core.cljs:160)
    at clara$rules$accumulators$accum (accumulators.cljc:26)
    at clara$rules$accumulators$count (accumulators.cljc:164)
    at rules.cljs:100
cljs$core$missing_protocol @ core.cljs:281
schema$core$spec @ core.cljs:109
(anonymous) @ core.cljs:134
schema$spec$core$run_checker @ core.cljs:69
schema$core$checker @ core.cljs:133
schema$core$validator @ core.cljs:148
schema$core$validate @ core.cljs:160
clara$rules$accumulators$accum @ accumulators.cljc:26
clara$rules$accumulators$count @ accumulators.cljc:164
(anonymous) @ rules.cljs:100
engine.cljc:75 Uncaught Error: No protocol method ISession.components defined for type undefined: 
    at cljs$core$missing_protocol (core.cljs:281)
    at clara$rules$engine$components (engine.cljc:75)
    at precept$listeners$remove_fact_listeners (listeners.cljc:72)
    at precept$listeners$replace_listener (listeners.cljc:156)
    at precept$core$start_BANG_ (core.cljc:218)
    at precept$todomvc$core$main (core.cljs:31)
    at app.cljs:8
cljs$core$missing_protocol @ core.cljs:281
clara$rules$engine$components @ engine.cljc:75
precept$listeners$remove_fact_listeners @ listeners.cljc:72
precept$listeners$replace_listener @ listeners.cljc:156
precept$core$start_BANG_ @ core.cljc:218
precept$todomvc$core$main @ core.cljs:31
(anonymous) @ app.cljs:8
```

**Comment by kennyjwilli** [comment]
How are you getting this output? Are you running the tests differently?

**Comment by alex-dixon** [comment]
Sorry. Ran lein figwheel.

**Comment by kennyjwilli** [comment]
Ok, I am seeing the warnings but no stack trace. How are you getting the error?

**Comment by kennyjwilli** [comment]
Updating to the latest prismatic/schema gets rid of the warnings.

**Comment by alex-dixon** [comment]
@kennyjwilli Thanks again for this. Should be able to merge soon according to Mr. Brush. https://twitter.com/ryanbrush/status/879043900819861504

**Pull request merged**
